version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maintenance
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: index-maintenance-app
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/your_database
      QUARKUS_DATASOURCE_USERNAME: your_user
      QUARKUS_DATASOURCE_PASSWORD: your_password
    ports:
      - "8080:8080"

volumes:
  postgres-data:
