version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maintenance
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: hbbucker/index-maintenance:latest
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    container_name: index-maintenance-app
    depends_on:
      - db
    environment:
      DATABASE_CONFIG_FILE: /app/database.conf
    volumes:
        - /your/config/file/database.conf:/app/database.conf
    ports:
      - "8080:8080"

volumes:
  postgres-data:
